Fix GeoJsonDataProvider caused by improper async usage in TilerService.
Fixes

   Error: DataCloneError: Failed to execute 'postMessage' on
      'DedicatedWorkerGlobalScope': #<Promise> could not be cloned

error cause introduced in #526.

Signed-off-by: Zbigniew Zagorski <ext-zbyszek.zagorski@here.com>